debugMode : true
kitsunekkoCachePath : ./cache/kitsunekko.html
releaseStoragePath : ./storage/test.txt
fileStorageFolder : ./storage/
animeUrlCollection: animeurlcollection
animeSubsCollection: animesubscollection